Add tests to reproduce error when used only .catch without .then
We can't only catch errors for request
```js
const superagent = require('superagent')

superagent
  .get('https://ya.ru')
  .catch(err => console.log(err))
```

Output:
```
  .catch(err => console.log(err))
        ^

TypeError: superagent.get(...).catch is not a function
```

But in promises we can:

```js
Promise.reject('Error!')
  .catch(err => {
    console.log(err) // Error!
  })

Promise.resolve(123)
  .catch(err => {
    // no errors
    console.log(err)
  })
```